config = {
    "fps": 15,
    "url_limit": 1,
    "batch_size": 10,
    "max_frames": 100,
    "max_open_warning": 100,
    "logging_level": "WARNING",
    "logging_format": "[%(levelname)s] %(asctime)s: %(message)s",
    "logging_datefmt": "%I:%M%p",
    "logging_color": "\x1b[31;1m",
    "logging_reset": "\x1b[0m",
    "scratch_dir": "streamwee_scratch",
    "output_path": "streamwee",
    "mp4_codec": "libx264",
    "gif_loop": 0,
    "gif_pause": 2,
}
