name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip build
          python -m pip install --upgrade --upgrade-strategy eager -e .

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-package
          path: "./dist"

  publish-release:
    name: Publish release to PyPI
    needs: [build-release]
    environment: "prod"
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-package
          path: './dist'

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
